services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y build-essential libssl-dev libffi-dev python3-dev
      apt-get install -y libopencv-dev python3-opencv
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion:  3.12.3
